/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cardmodule.CardPersonalization;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.smartcardio.CardException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Desktop
 */
public class Gui extends javax.swing.JFrame {

    
    CardPersonalization cardAPI;
    
    
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        
         try {        
            cardAPI = new CardPersonalization();
            
            for(Object c: cardAPI.getCardReaders()){
                cardSelection_CB.addItem(c);
            }
            
        } catch (CardException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    private void openFileChoose(JTextField tf, final String extension, final String extensionDescription){
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.setAcceptAllFileFilterUsed(false);

        FileFilter filter = new FileFilter() {

            @Override
            public boolean accept(File pathname) {
                return pathname.getName().toLowerCase().endsWith(extension) || pathname.isDirectory();
            }

            @Override
            public String getDescription() {
                return extensionDescription;
            }
        };

        chooser.setFileFilter(filter);

        int r = chooser.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            tf.setText( chooser.getSelectedFile().getPath());
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        card_pin_TF = new javax.swing.JTextField();
        enc_key_TF = new javax.swing.JTextField();
        enc_choose_BT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sig_key_TF = new javax.swing.JTextField();
        sig_choose_BT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        keystore_TF = new javax.swing.JTextField();
        ks_choose_BT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rsaKey_TF = new javax.swing.JTextField();
        rsa_choose_BT = new javax.swing.JButton();
        send_BT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console_TA = new javax.swing.JTextArea();
        cardSelection_CB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Card Pin");

        card_pin_TF.setText("12345678");

        enc_choose_BT.setText("Choose");
        enc_choose_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enc_choose_BTActionPerformed(evt);
            }
        });

        jLabel2.setText("Encryption/Decryption Secret Key");

        jLabel3.setText("Signature Secret Key");

        sig_choose_BT.setText("Choose");
        sig_choose_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sig_choose_BTActionPerformed(evt);
            }
        });

        jLabel4.setText("User Key Store");

        ks_choose_BT.setText("Choose");
        ks_choose_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ks_choose_BTActionPerformed(evt);
            }
        });

        jLabel5.setText("RSA Private Key");

        rsa_choose_BT.setText("Choose");
        rsa_choose_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsa_choose_BTActionPerformed(evt);
            }
        });

        send_BT.setText("Send");
        send_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_BTActionPerformed(evt);
            }
        });

        console_TA.setColumns(20);
        console_TA.setRows(5);
        jScrollPane1.setViewportView(console_TA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cardSelection_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rsaKey_TF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(keystore_TF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sig_key_TF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enc_key_TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rsa_choose_BT)
                                    .addComponent(enc_choose_BT)
                                    .addComponent(sig_choose_BT)
                                    .addComponent(ks_choose_BT)))
                            .addComponent(card_pin_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(send_BT)
                                .addGap(106, 106, 106))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardSelection_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(card_pin_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_BT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enc_key_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enc_choose_BT)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sig_key_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sig_choose_BT))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(keystore_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ks_choose_BT))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rsaKey_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rsa_choose_BT)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enc_choose_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enc_choose_BTActionPerformed
        openFileChoose(enc_key_TF, ".key", "3DES Secret Key File (.key)");
    }//GEN-LAST:event_enc_choose_BTActionPerformed

    private void sig_choose_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sig_choose_BTActionPerformed
        openFileChoose(sig_key_TF, ".key", "3DES Secret Key File (.key)");
    }//GEN-LAST:event_sig_choose_BTActionPerformed

    private void ks_choose_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ks_choose_BTActionPerformed
        openFileChoose(keystore_TF, ".p12", "PKCS#12 Keystore File (.p12)");
    }//GEN-LAST:event_ks_choose_BTActionPerformed

    private void rsa_choose_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsa_choose_BTActionPerformed
        openFileChoose(rsaKey_TF, ".key", "RSA Private Key File (.key)");
    }//GEN-LAST:event_rsa_choose_BTActionPerformed

    private void send_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_BTActionPerformed
        
        if(card_pin_TF.getText().equals("") ||
                enc_key_TF.getText().equals("") ||
                sig_key_TF.getText().equals("") ||
                rsaKey_TF.getText().equals("") ||
                keystore_TF.getText().equals("")){
            
            JOptionPane.showMessageDialog(this,
                "Fill all the boxes.\n",
                "Warning",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        
        
        cardAPI.setCardReader(cardSelection_CB.getSelectedIndex());
        cardAPI.sendToCard(card_pin_TF.getText(),
                enc_key_TF.getText(),
                sig_key_TF.getText(), 
                rsaKey_TF.getText(),
                keystore_TF.getText()
                , console_TA);
        
    }//GEN-LAST:event_send_BTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cardSelection_CB;
    private javax.swing.JTextField card_pin_TF;
    private javax.swing.JTextArea console_TA;
    private javax.swing.JButton enc_choose_BT;
    private javax.swing.JTextField enc_key_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keystore_TF;
    private javax.swing.JButton ks_choose_BT;
    private javax.swing.JTextField rsaKey_TF;
    private javax.swing.JButton rsa_choose_BT;
    private javax.swing.JButton send_BT;
    private javax.swing.JButton sig_choose_BT;
    private javax.swing.JTextField sig_key_TF;
    // End of variables declaration//GEN-END:variables
}
